### ISSUE TITLE
Put `.java` files in `src` directory

### ISSUE THREAD

**Issue by mangkoran** [mangkoran/oop-project#3]
Source files should be put inside its own `src` directory. It will look more or less like this:
```
└── src
    ├── Food.java
    └── etc..
```

**Comment by mangkoran** [comment]
@leonnahart Could you do the change and create new PR for this?

**Comment by leonnahart** [comment]
On it

**Comment by mangkoran** [comment]
Closed with https://github.com/mangkoran/oop-project/pull/4
